openapi: "3.0.0"
info:
  title: "Planning Poker API"
  version: "1.0.0"
  description: "API para gerenciamento de salas e votação no Planning Poker"
servers:
  - url: "http://localhost:3000"
    description: "Servidor Local"

paths:
  /api/poker/create-room:
    post:
      summary: "Cria uma nova sala de Planning Poker"
      responses:
        200:
          description: "Retorna o ID da sala criada"
          content:
            application/json:
              schema:
                type: object
                properties:
                  roomId:
                    type: string

  /api/poker/join-room:
    post:
      summary: "Permite que um jogador entre em uma sala"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomId:
                  type: string
                playerName:
                  type: string
      responses:
        200:
          description: "Retorna o ID do jogador"
          content:
            application/json:
              schema:
                type: object
                properties:
                  playerId:
                    type: string

  /api/poker/room/{roomId}/players:
    get:
      summary: "Retorna a lista de jogadores de uma sala"
      parameters:
        - in: path
          name: roomId
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Retorna a lista de jogadores da sala"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    vote:
                      type: string
                      nullable: true

  /api/poker/room/{roomId}/reset:
    post:
      summary: "Reinicia a votação em uma sala"
      parameters:
        - in: path
          name: roomId
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Confirmação da reinicialização da votação"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
